# Generated by Django 2.2.12 on 2024-05-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogger', '0002_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Blogger',
        ),
    ]
