# Generated by Django 2.2.12 on 2024-05-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogger', '0005_imageblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cuerpo',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
