# Generated by Django 2.2.12 on 2024-05-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogger', '0009_auto_20240502_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
