# Generated by Django 2.2.12 on 2024-05-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogger', '0011_auto_20240502_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
