# Generated by Django 2.2.12 on 2024-05-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogger', '0012_delete_blogger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageBlog',
        ),
    ]
